package com.sap.events.jersy.services.error;

public enum ErrorCode {
	UNDEFINED_ERROR, //
	UNEXPECTED_ERROR, //
	INVALID_SECRET, //
	INVALID_USER, //
	INVALID_PASSWORD, //
	NO_DIRECT_DEBITS_FOR_ACCOUNT, //
	VALIDATION_ERROR, //
	PAYEE_NOT_FOUND, //
	PAYEE_ALREADY_EXISTS, //
	PAYEE_GROUP_NOT_FOUND, //
	PAYEE_GROUP_ALREADY_EXISTS, //
	AMOUNT_EXCEEDS_ALLOWABLE_VALUES, //
	USER_BLOCKED, //
	PAYMENT_REFERENCE_NUMBER_IS_INVALID, //
	USER_ALREADY_EXISTS//
}
